# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Juan Nunez-Iglesias'
tagline:          'Bioinformatics research scientist'
description:      ''
url:              http://jni.github.io/
baseurl:          http://jni.github.io/

author:
  name:           'Juan Nunez-Iglesias'
  url:            https://twitter.com/jnuneziglesias

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jni/jni.github.io
